// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllPlans() {
  return window['go']['backend']['App']['GetAllPlans']();
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function GetExercises(arg1) {
  return window['go']['backend']['App']['GetExercises'](arg1);
}

export function GetExercisesByIDs(arg1) {
  return window['go']['backend']['App']['GetExercisesByIDs'](arg1);
}

export function GetImgPrefix() {
  return window['go']['backend']['App']['GetImgPrefix']();
}

export function GetLastWorkout(arg1) {
  return window['go']['backend']['App']['GetLastWorkout'](arg1);
}

export function GetPlan(arg1) {
  return window['go']['backend']['App']['GetPlan'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['backend']['App']['SaveConfig'](arg1);
}

export function SavePlan(arg1) {
  return window['go']['backend']['App']['SavePlan'](arg1);
}

export function StartWorkout() {
  return window['go']['backend']['App']['StartWorkout']();
}

export function WorkoutExitDialog() {
  return window['go']['backend']['App']['WorkoutExitDialog']();
}

export function WorkoutSaveDialog(arg1) {
  return window['go']['backend']['App']['WorkoutSaveDialog'](arg1);
}
