// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetAllPlans():Promise<Array<backend.Plan>>;

export function GetConfig():Promise<backend.Config>;

export function GetExercises(arg1:string):Promise<Array<backend.Exercise>>;

export function GetExercisesByIDs(arg1:Array<string>):Promise<Array<backend.Exercise>>;

export function GetImgPrefix():Promise<string>;

export function GetLastWorkout(arg1:string):Promise<backend.Progress>;

export function GetPlan(arg1:string):Promise<backend.Plan>;

export function SaveConfig(arg1:backend.Config):Promise<void>;

export function SavePlan(arg1:backend.Plan):Promise<boolean>;

export function StartWorkout():Promise<void>;

export function WorkoutExitDialog():Promise<boolean>;

export function WorkoutSaveDialog(arg1:backend.PlanDay):Promise<boolean>;
