name: Build and Publish Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t goains_builder .

      - name: Run Docker container to build binaries
        run: docker run --rm -v ${{ github.workspace }}/build/bin:/artifacts goains_builder

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: goains-binaries
          path: build/bin/