// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllPlans():Promise<Array<main.Plan>>;

export function GetConfig():Promise<main.Config>;

export function GetExercises(arg1:string):Promise<Array<main.Exercise>>;

export function GetExercisesByIDs(arg1:Array<string>):Promise<Array<main.Exercise>>;

export function GetImgPrefix():Promise<string>;

export function GetLastWorkout(arg1:string):Promise<main.Progress>;

export function GetPlan(arg1:string):Promise<main.Plan>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SavePlan(arg1:main.Plan):Promise<boolean>;

export function StartWorkout():Promise<void>;

export function WorkoutExitDialog():Promise<boolean>;

export function WorkoutSaveDialog(arg1:main.PlanDay):Promise<boolean>;
