// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadDatabase():Promise<void>;

export function GetExercises(arg1:string):Promise<Array<main.Exercise>>;

export function GetImgPrefix():Promise<string>;

export function HasPlan():Promise<boolean>;
