// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllPlans():Promise<Array<main.Plan>>;

export function GetConfig():Promise<main.Config>;

export function GetExercises(arg1:string):Promise<Array<main.Exercise>>;

export function GetImgPrefix():Promise<string>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SavePlan(arg1:main.Plan):Promise<void>;

export function SetCurrentPlan(arg1:string):Promise<void>;
