// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetExercises(arg1) {
  return window['go']['main']['App']['GetExercises'](arg1);
}

export function GetImgPrefix() {
  return window['go']['main']['App']['GetImgPrefix']();
}

export function HasPlan() {
  return window['go']['main']['App']['HasPlan']();
}
